# Python Numpy Notebook

Video Title: numpy tutorial - introduction | numpy array vs python list 

Video URL: https://youtu.be/rN0TREj8G7U?list=PLeo1K3hjS3uset9zIVzJWqplaWBiacTEU

In [1]:
# Import numpy library
import numpy as np

In [9]:
# Create a numpy array
a1 = np.array([1,2,3])
a


array([1, 2, 3])

In [10]:
a1[0]

1

In [11]:
# Acces the element from array
a1[2]

3

In [12]:
a2 =np.array([6,5,4])
a2

array([6, 5, 4])

In [13]:
a1+a2

array([7, 7, 7])

In [14]:
a1-a2

array([-5, -3, -1])

In [15]:
a1*a2

array([ 6, 10, 12])

In [16]:
a1/a2

array([0.16666667, 0.4       , 0.75      ])

Video title: numpy tutorial - basic array operations

Video URL: https://youtu.be/a8aDcLk4vRc?list=PLeo1K3hjS3uset9zIVzJWqplaWBiacTEU

In [18]:
# to check the dimension of array
a1.ndim

1

In [22]:
# Create a 2 dimensional array and print it

b1 = np.array([[1,2],[4,5]])
b1.ndim

2

In [23]:
b2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
b2.ndim

2

In [24]:
b2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
# to know the item size of array
b2.itemsize

8

In [28]:
# to check the data type of array
b1.dtype

dtype('int64')

In [30]:
# create a float array and check its data type
c1 = np.array([1.1,2.2,3.3])
c1

array([1.1, 2.2, 3.3])

In [31]:
c1.itemsize

8

In [32]:
c1.dtype

dtype('float64')

In [33]:
# change the data type of array from int to float
b1 = np.array([[1,2],[4,5]], dtype = np.float64)
b1.dtype

dtype('float64')

In [34]:
b1

array([[1., 2.],
       [4., 5.]])

In [36]:
# to check the shape property of data
b1.shape

(2, 2)

In [37]:
b2.shape

(3, 3)

In [38]:
# change the data type of array from float to complex number

b1 = np.array([[1,2],[4,5]], dtype = np.complex)
b1.dtype

/var/folders/dh/7xx99shn2snbzfm45j_y40f9p0zqn5/T/ipykernel_86703/2420667287.py:3: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b1 = np.array([[1,2],[4,5]], dtype = np.complex)


dtype('complex128')

In [39]:
b1

array([[1.+0.j, 2.+0.j],
       [4.+0.j, 5.+0.j]])

In [41]:
# initialise array with zeros
e1 = np.zeros((3,4))
e1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
e1.dtype

dtype('float64')

In [44]:
# initialise array with ones (1)
e2 = np.ones((2,4))
e2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
# Create a array using arange
f = np.arange(0,5)
f

array([0, 1, 2, 3, 4])

In [51]:
# Create a array using range but with the step of 2
g = np.arange(0,8,2)
g

array([0, 2, 4, 6])

In [52]:
# Create a array using linear space from 0 to 5
h1 = np.linspace(0,2,10)
h1

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [54]:
h2 = np.linspace(1,5,5)
h2

array([1., 2., 3., 4., 5.])

In [55]:
# Create a new array and Reshape its dimensions 
i = np.array([[1,2,3],[4,5,6]])
i

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
i.shape

(2, 3)

In [57]:
i.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
i.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [62]:
# Flatten your array (It will make your array as one Dimensional)
i.ravel()

array([1, 2, 3, 4, 5, 6])

In [63]:
b.ravel()

array([1, 2, 4, 5])

In [64]:
# Check some numpy mathematical functions
# Check min number from array
i.min()


1

In [66]:
# Check max number from array
i.max()

6

In [67]:
# Sum all number of array
i.sum()

21

 In array "i" [1,4] is the axis = 1 and [1,2,3] is the axis = 0

In [68]:
i

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
# sum the axis = 1 of array (Horizontal Sum)
i.sum(axis=1)

array([ 6, 15])

In [70]:
# Sum the axis = 0 of array (Vertical Sum)
i.sum(axis=0)

array([5, 7, 9])

In [71]:
# Do square root of array
np.sqrt(i)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [72]:
np.sqrt(i).dtype

dtype('float64')

In [73]:
np.sqrt(i).shape

(2, 3)

In [75]:
# check the standard deviations of array
np.std(i)

1.707825127659933

In [77]:
j = np.array([[1,2],[3,4]]) 
k = np.array([[5,6],[7,8]])

In [78]:
j

array([[1, 2],
       [3, 4]])

In [79]:
k

array([[5, 6],
       [7, 8]])

In [82]:
# Adding 2 array
j+k

array([[ 6,  8],
       [10, 12]])

In [83]:
# Multiply 2 array
j*k

array([[ 5, 12],
       [21, 32]])

In [86]:
# matrix Product of 2 array
j.dot(k)

array([[19, 22],
       [43, 50]])

Video Title: numpy tutorial - slicing/stacking arrays, indexing with boolean arrays

Video URL: https://youtu.be/_d_Ka-ks2a0?list=PLeo1K3hjS3uset9zIVzJWqplaWBiacTEU

In [92]:
n = [6,7,8]

In [93]:
n[0]

6

In [94]:
n[0:2]

[6, 7]

In [95]:
n[-1]

8

In [99]:
# Slicing the array
m = np.array([6,7,8])
m

array([6, 7, 8])

In [98]:
m[0:2]

array([6, 7])

In [100]:
n = np.array([[6,7,8],[1,2,3],[9,3,2]])
n

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [101]:
n[1,2]

3

In [103]:
n[2,0]

9

In [104]:
n[0:2]

array([[6, 7, 8],
       [1, 2, 3]])

In [105]:
n[1:2]

array([[1, 2, 3]])

In [106]:
n[1:3]

array([[1, 2, 3],
       [9, 3, 2]])

In [107]:
n[0:2,2]

array([8, 3])

In [108]:
n[0:2,1]

array([7, 2])

In [109]:
n[-1]

array([9, 3, 2])

In [110]:
n[-1,0:2]

array([9, 3])

In [111]:
n[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

Iterate through array

In [113]:
for row in n:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [114]:
for cell in n.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [118]:
# Stacking 2 array together 
# Vertical Stacking 2 arrays

np.vstack((j,k))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [117]:
# horizontal stacking 2 arrays
np.hstack((j,k))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [120]:
p = np.arange(30).reshape(2,15)
p

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

Array Slicing

In [123]:
result = np.hsplit(p,3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [125]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [126]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [127]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [128]:
p

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [134]:
result1 = np.vsplit(p,2)
result1

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [136]:
result1[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [135]:
result1[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [155]:
# Indexing with Boolean Array
q = np.arange(12).reshape(3,4)
q

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
r = q > 4
r

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [142]:
r = q>1
r

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [153]:
q[r]

array([ 5,  6,  7,  8,  9, 10, 11])

In [156]:
q[r]= -1
q

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

Video Title: numpy tutorial: iterate numpy array using nditer | numpy nditer

Video URL: https://youtu.be/XawR6CjAYV4?list=PLeo1K3hjS3uset9zIVzJWqplaWBiacTEU

In [188]:
y = np.arange(12).reshape(3,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [159]:
for row in y:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [163]:
for row in y:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [164]:
for row in y.flatten():
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11


Use of nditer() function

In [166]:
for x in np.nditer(y,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [167]:
# Use fortan order

for z in np.nditer(y,order='F'):
    print(z)

0
4
8
1
5
9
2
6
10
3
7
11


In [169]:
# C Order  0>1>2>3>4>5>6>7>8>9>10>11
# F (Fortran) Order 0>4>8>1>5>9>2>6>10>3>7>11

y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [170]:
for zx in np.nditer(y,order='F',flags=['external_loop']):
    print(zx)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [191]:
for x in np.nditer(y,op_flags=['readwrite']):
    x[...]=x * x

In [185]:
y

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [186]:
z = np.arange(3,15,4).reshape(3,1)
z

array([[ 3],
       [ 7],
       [11]])

In [192]:
for ya,za in np.nditer ([y,z]):
    print(ya,za)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


Reference Notebook URL: https://github.com/codebasics/py/blob/master/numpy/nditer.ipynb